[package]
name = "codexec-exec-engine"
version.workspace = true
edition.workspace = true

[dependencies]
codexec-exec-contract.workspace = true
tokio.workspace = true
oci-spec = { version = "0.10", features = ["runtime"] }
tempfile = "3"
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
async-trait.workspace = true
